-- Create posts table
create table public.posts (
  id bigint generated by default as identity primary key,
  content text not null,
  timestamp bigint not null,
  likes integer default 0,
  from_suggestion boolean default false,
  created_at timestamptz default now()
);

-- Create suggestions table
create table public.suggestions (
  id bigint generated by default as identity primary key,
  content text not null,
  timestamp bigint not null,
  created_at timestamptz default now()
);

-- Enable Row Level Security
alter table public.posts enable row level security;
alter table public.suggestions enable row level security;

-- Public read policy for posts
create policy "Public can read posts" 
  on public.posts
  for select
  using (true);

-- Authenticated users can insert/update/delete posts
create policy "Authenticated users can manage posts" 
  on public.posts
  for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

-- Secure function that ONLY allows incrementing the likes column
-- This prevents public users from modifying any other columns
create or replace function public.increment_post_likes(post_id bigint)
returns void
language plpgsql
security definer
as $$
begin
  update public.posts
  set likes = likes + 1
  where id = post_id;
end;
$$;

-- Grant execute permission to public (anon) and authenticated users
grant execute on function public.increment_post_likes(bigint) to anon, authenticated;

-- Public can read suggestions
create policy "Public can read suggestions" 
  on public.suggestions
  for select
  using (true);

-- Anyone can insert suggestions (public)
create policy "Anyone can create suggestions" 
  on public.suggestions
  for insert
  with check (true);

-- Authenticated users can delete suggestions
create policy "Authenticated users can delete suggestions" 
  on public.suggestions
  for delete
  using (auth.role() = 'authenticated');

-- Create playlist_settings table
create table public.playlist_settings (
  id bigint generated by default as identity primary key,
  playlist_url text,
  playlist_type text default 'youtube',
  updated_at timestamptz default now(),
  updated_by uuid references auth.users(id)
);

-- Enable Row Level Security
alter table public.playlist_settings enable row level security;

-- Public can read playlist settings
create policy "Public can read playlist settings" 
  on public.playlist_settings
  for select
  using (true);

-- Only authenticated users can insert/update playlist settings
create policy "Authenticated users can manage playlist settings" 
  on public.playlist_settings
  for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

-- Insert a single row (singleton pattern)
insert into public.playlist_settings (id, playlist_url, playlist_type) 
values (1, null, 'youtube') 
on conflict (id) do nothing;

-- Add tag column to posts table (migration)
alter table public.posts 
add column if not exists tag text;

-- Create letterboxd_settings table
create table if not exists public.letterboxd_settings (
  id bigint generated by default as identity primary key,
  letterboxd_url text,
  updated_at timestamptz default now(),
  updated_by uuid references auth.users(id)
);

-- Enable Row Level Security
alter table public.letterboxd_settings enable row level security;

-- Public can read letterboxd settings
create policy "Public can read letterboxd settings" 
  on public.letterboxd_settings
  for select
  using (true);

-- Only authenticated users can manage letterboxd settings
create policy "Authenticated users can manage letterboxd settings" 
  on public.letterboxd_settings
  for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

-- Insert a single row (singleton pattern)
insert into public.letterboxd_settings (id, letterboxd_url) 
values (1, null) 
on conflict (id) do nothing;

-- Create letterboxd_reviews table
create table if not exists public.letterboxd_reviews (
  id bigint generated by default as identity primary key,
  review_url text not null unique,
  film_title text not null,
  film_year text,
  review_text text,
  rating text,
  watched_date text,
  review_timestamp bigint not null,
  is_selected boolean default false,
  letterboxd_username text,
  created_at timestamptz default now()
);

-- Add username column if it doesn't exist (migration)
alter table public.letterboxd_reviews 
add column if not exists letterboxd_username text;

-- Enable Row Level Security
alter table public.letterboxd_reviews enable row level security;

-- Public can read letterboxd reviews
create policy "Public can read letterboxd reviews" 
  on public.letterboxd_reviews
  for select
  using (true);

-- Only authenticated users can manage letterboxd reviews
create policy "Authenticated users can manage letterboxd reviews" 
  on public.letterboxd_reviews
  for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

