-- Create posts table
create table public.posts (
  id bigint generated by default as identity primary key,
  content text not null,
  timestamp bigint not null,
  likes integer default 0,
  from_suggestion boolean default false,
  created_at timestamptz default now()
);

-- Create suggestions table
create table public.suggestions (
  id bigint generated by default as identity primary key,
  content text not null,
  timestamp bigint not null,
  created_at timestamptz default now()
);

-- Enable Row Level Security
alter table public.posts enable row level security;
alter table public.suggestions enable row level security;

-- Public read policy for posts
create policy "Public can read posts" 
  on public.posts
  for select
  using (true);

-- Authenticated users can insert/update/delete posts
create policy "Authenticated users can manage posts" 
  on public.posts
  for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

-- Public can read suggestions
create policy "Public can read suggestions" 
  on public.suggestions
  for select
  using (true);

-- Anyone can insert suggestions (public)
create policy "Anyone can create suggestions" 
  on public.suggestions
  for insert
  with check (true);

-- Authenticated users can delete suggestions
create policy "Authenticated users can delete suggestions" 
  on public.suggestions
  for delete
  using (auth.role() = 'authenticated');

-- Create playlist_settings table
create table public.playlist_settings (
  id bigint generated by default as identity primary key,
  playlist_url text,
  playlist_type text default 'youtube',
  updated_at timestamptz default now(),
  updated_by uuid references auth.users(id)
);

-- Enable Row Level Security
alter table public.playlist_settings enable row level security;

-- Public can read playlist settings
create policy "Public can read playlist settings" 
  on public.playlist_settings
  for select
  using (true);

-- Only authenticated users can insert/update playlist settings
create policy "Authenticated users can manage playlist settings" 
  on public.playlist_settings
  for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

-- Insert a single row (singleton pattern)
insert into public.playlist_settings (id, playlist_url, playlist_type) 
values (1, null, 'youtube') 
on conflict (id) do nothing;

